spin_manifest_version = 2

[application]
name = "spin-wasi-http"
version = "0.1.0"
authors = ["Adam Reese <adam@reese.io>"]
description = ""

[variables]
object = { default = "teapot" }

[[trigger.http]]
route = "/..."
component = "spin-wasi-http"

[component.spin-wasi-http]
source = "main.wasm"
allowed_outbound_hosts = []
[component.spin-wasi-http.variables]
message = "I'm a {{object}}"
[component.spin-wasi-http.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/spinframework/spin-go-sdk/v2)/wit --wit-world http-trigger -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
